# Generated by Django 4.2.6 on 2023-10-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_prato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='descricao',
            field=models.CharField(default='Descrição', max_length=50),
        ),
        migrations.AlterField(
            model_name='prato',
            name='foto',
            field=models.ImageField(default='images.jpeg', upload_to=''),
        ),
    ]
