# Generated by Django 4.2.6 on 2024-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_alter_prato_descricao_alter_prato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
