# Generated by Django 4.2.6 on 2023-10-29 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hamburgueria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='FaixaFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distancia_maxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hamburgueria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frete.hamburgueria')),
            ],
        ),
    ]
