# Generated by Django 4.2.6 on 2024-03-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburgueria',
            name='latitude',
            field=models.DecimalField(decimal_places=14, max_digits=18),
        ),
        migrations.AlterField(
            model_name='hamburgueria',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=18),
        ),
    ]
