# Generated by Django 4.2.6 on 2024-05-22 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0002_pedidoprato_desconto_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoprato',
            name='desconto_unitario',
        ),
        migrations.RemoveField(
            model_name='pedidoprato',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='pedidoprato',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
