# Generated by Django 4.2.6 on 2024-05-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_remove_pedidoprato_desconto_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoprato',
            name='desconto_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidoprato',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
